# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build-Publish

on:
  push:
    tags: 'v*'
  
jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    env:
      SOURCE_NAME: ${{ steps.branch_name.outputs.SOURCE_NAME }}
      SOURCE_BRANCH: ${{ steps.branch_name.outputs.SOURCE_BRANCH }}
      SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - uses: actions/checkout@v1
    - name: Build
      run: echo 'test' #mvn -B package --file ScrumTool/pom.xml -Pproduction
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GH_TOKEN }}
        file: ScrumTool/target/ScrumTool-1.0-SNAPSHOT.jar
        asset_name: ScrumTool.jar
        tag: ${{ SOURCE_TAG }}
        overwrite: true
