# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build-Publish

on:
  push:
    tags: 'v*'
  
jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - uses: actions/checkout@v1
    - name: Set output
      id: var
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Check output
      env:
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: |
        echo $RELEASE_VERSION
        echo ${{ steps.vars.outputs.tag }}
    - name: Build
      run: echo 'test' #mvn -B package --file ScrumTool/pom.xml -Pproduction
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GH_TOKEN }}
        file: ScrumTool/target/ScrumTool-1.0-SNAPSHOT.jar
        asset_name: ScrumTool.jar
        tag: ${{ steps.vars.outputs.tag }}
        overwrite: true
